Creating dataloaders for path: dakshina_dataset_v1.0/hi/lexicons/
Files in directory: ['hi.translit.sampled.dev.tsv', 'temp_nan.tsv', 'hi.translit.sampled.train.tsv', 'hi.translit.sampled.test.tsv']
Loading data from: dakshina_dataset_v1.0/hi/lexicons/hi.translit.sampled.train.tsv
Loaded with pandas (tab): (44204, 3)
Skipping NaN string at row 19724: рдирди -> none
Extracted 44201 valid pairs from DataFrame
Loaded 44201 valid data pairs
Latin vocabulary size: 67
Devanagari vocabulary size: 30
Files in directory: ['hi.translit.sampled.dev.tsv', 'temp_nan.tsv', 'hi.translit.sampled.train.tsv', 'hi.translit.sampled.test.tsv']
Loading data from: dakshina_dataset_v1.0/hi/lexicons/hi.translit.sampled.dev.tsv
Loaded with pandas (tab): (4358, 3)
Extracted 4358 valid pairs from DataFrame
Loaded 4358 valid data pairs
Latin vocabulary size: 65
Devanagari vocabulary size: 30
Files in directory: ['hi.translit.sampled.dev.tsv', 'temp_nan.tsv', 'hi.translit.sampled.train.tsv', 'hi.translit.sampled.test.tsv']
Loading data from: dakshina_dataset_v1.0/hi/lexicons/hi.translit.sampled.test.tsv
Loaded with pandas (tab): (4502, 3)
Extracted 4502 valid pairs from DataFrame
Loaded 4502 valid data pairs
Latin vocabulary size: 65
Devanagari vocabulary size: 30
Created dataloaders - Train: 44201 samples, Dev: 4358 samples, Test: 4502 samples
The model has 208,734 trainable parameters
Traceback (most recent call last):                                                                                                                                                
  File "/speech/utkarsh/da6401_assignment3/main.py", line 178, in <module>
    main(config)
  File "/speech/utkarsh/da6401_assignment3/main.py", line 80, in main
    history = train_model(
  File "/speech/utkarsh/da6401_assignment3/train.py", line 211, in train_model
    train_loss = train(model, train_iterator, optimizer, criterion, clip, device)
  File "/speech/utkarsh/da6401_assignment3/train.py", line 35, in train
    for i, (src, trg) in enumerate(tqdm(iterator, desc="Training", leave=False)):
  File "/speech/utkarsh/.local/lib/python3.10/site-packages/tqdm/std.py", line 1181, in __iter__
    for obj in iterable:
  File "/speech/utkarsh/.local/lib/python3.10/site-packages/torch/utils/data/dataloader.py", line 530, in __next__
    data = self._next_data()
  File "/speech/utkarsh/.local/lib/python3.10/site-packages/torch/utils/data/dataloader.py", line 570, in _next_data
    data = self._dataset_fetcher.fetch(index)  # may raise StopIteration
  File "/speech/utkarsh/.local/lib/python3.10/site-packages/torch/utils/data/_utils/fetch.py", line 49, in fetch
    data = [self.dataset[idx] for idx in possibly_batched_index]
  File "/speech/utkarsh/.local/lib/python3.10/site-packages/torch/utils/data/_utils/fetch.py", line 49, in <listcomp>
    data = [self.dataset[idx] for idx in possibly_batched_index]
  File "/speech/utkarsh/da6401_assignment3/data.py", line 242, in __getitem__
    devanagari_indices = [self.devanagari_char2idx['< SOS >']]
KeyError: '< SOS >'
Traceback (most recent call last):
  File "/speech/utkarsh/da6401_assignment3/main.py", line 178, in <module>
    main(config)
  File "/speech/utkarsh/da6401_assignment3/main.py", line 80, in main
    history = train_model(
  File "/speech/utkarsh/da6401_assignment3/train.py", line 211, in train_model
    train_loss = train(model, train_iterator, optimizer, criterion, clip, device)
  File "/speech/utkarsh/da6401_assignment3/train.py", line 35, in train
    for i, (src, trg) in enumerate(tqdm(iterator, desc="Training", leave=False)):
  File "/speech/utkarsh/.local/lib/python3.10/site-packages/tqdm/std.py", line 1181, in __iter__
    for obj in iterable:
  File "/speech/utkarsh/.local/lib/python3.10/site-packages/torch/utils/data/dataloader.py", line 530, in __next__
    data = self._next_data()
  File "/speech/utkarsh/.local/lib/python3.10/site-packages/torch/utils/data/dataloader.py", line 570, in _next_data
    data = self._dataset_fetcher.fetch(index)  # may raise StopIteration
  File "/speech/utkarsh/.local/lib/python3.10/site-packages/torch/utils/data/_utils/fetch.py", line 49, in fetch
    data = [self.dataset[idx] for idx in possibly_batched_index]
  File "/speech/utkarsh/.local/lib/python3.10/site-packages/torch/utils/data/_utils/fetch.py", line 49, in <listcomp>
    data = [self.dataset[idx] for idx in possibly_batched_index]
  File "/speech/utkarsh/da6401_assignment3/data.py", line 242, in __getitem__
    devanagari_indices = [self.devanagari_char2idx['< SOS >']]
KeyError: '< SOS >'
